USE SCOTT;

# LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL.
SELECT *
FROM EMP
WHERE COMM IS NULL;

# LIST ALL THE EMPLOYEES WHO DON’T HAVE REPORTING MANAGER
SELECT *
FROM EMP
WHERE MGR IS NULL;

# LIST ALL THE SALESMAN IN DEPT 30.
SELECT *
FROM EMP
WHERE JOB = 'SALESMAN' AND DEPTNO = 30;

# LIST ALL THE SALESMAN IN DEPT NUMBER 30 HAVING SALARY GREATER THAN 1500.
SELECT *
FROM EMP
WHERE DEPTNO = 30 AND SAL > 1500;

# WAQTD TOTAL NO OF EMP WORKING IN EACH JOB 
SELECT COUNT(*)
FROM EMP
GROUP BY JOB;

# WAQTD TOTAL NO OF EMP WORKING IN EACH DEPATMENT IF EACH DEPARTMENT CONSIST OF MORE THAN 3 EMP 
SELECT COUNT(*)
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) > 3;

# WAQTD tO DISPLAY MAXIMUM SALARY IN EACH JOB IF EACH JOB CONSIST OF MORE THAN 2 EMP AND EMP SHOULD BE HIRED BEFORE 88 AND 
# EMP SHOULD BE WORKING IN DEPT 20 OR 30 
SELECT JOB, MAX(SAL)
FROM EMP
WHERE HIREDATE < '1988-01-01' AND DEPTNO IN (20,30)
GROUP BY JOB
HAVING COUNT(*) > 2;

# WAQTD total number of employees working in each job if each job consists of more than 2 employees.
SELECT COUNT(*) 
FROM EMP
GROUP BY JOB 
HAVING COUNT(*) > 2;

# WAQTD department number and total salary of each department if total salary is greater than 8000.
SELECT DEPTNO, SUM(SAL)
FROM EMP
GROUP BY DEPTNO 
HAVING SUM(SAL) > 8000;


# WAQTD A SALARY WHICH IS REPEATED 
# WAQTD AN HIREDATE WHICH IS REPAETED 

SELECT SAL FROM EMP
GROUP BY SAL 
HAVING COUNT(*) > 1;

SELECT HIREDATE FROM EMP
GROUP BY HIREDATE 
HAVING COUNT(*) > 1;

# WAQTD job and average salary if the average salary is more than 2000.
SELECT JOB AND SAL 
FROM EMP
GROUP BY JOB AND SAL 
HAVING AVG(SAL) > 2000;

# WAQTD department number and number of employees if department has at least 4 employees.
SELECT DEPTNO AND COUNT(*)
FROM EMP
GROUP BY DEPTNO 
HAVING COUNT(*) >= 4;

# WAQTD manager number and total number of employees working under each manager if manager handles more than 1 employee.
SELECT COUNT(MGR) AND COUNT(*)
FROM EMP
GROUP BY MGR 
HAVING MGR > 1;

# WAQTD TOTAL NUMBER OF EMP IN EACH JOB IF EACH DEPATMENT IF EACH DEPARMENT CONSISIT OF 3 CLERK 
SELECT COUNT(*)
FROM EMP
WHERE JOB = 'CLERK'
GROUP BY JOB 
HAVING COUNT(*) > 1; 























