USE SCOTT;

#waqtd max salary minimum salaray avg salary total salary total no of emp working in each depatment, IF EACH DEPT CONSIST OF MORE 
#THAM & EMP $ MAX SAL LESS THAN 6000 AND MIN SAL MORE THAN 500 AND THIS EMP SHOULD BE HIRED IN 88 AND EMP SHOULD BE WORKING AS A 
#MANAGER, SALESMAN AS ANALYST 
SELECT DEPTNO, MIN(SAL), MAX(SAL), AVG(SAL), SUM(SAL), COUNT(*)
FROM EMP
WHERE HIREDATE LIKE '%88' AND JOB IN ('MANAGER','SALESMAN','ANALYST')
GROUP BY DEPTNO
HAVING COUNT(*) > 2 AND MAX(SAL) < 6000 AND MIN(SAL) > 500;

# WAQTD TO DISPLAY NO OF TIMES SAL IS REPEATED 
SELECT SAL, COUNT(*)
FROM EMP
GROUP BY SAL 
HAVING COUNT(*) > 1








