# NAME OF THE EMPLOYEE AND HIS LOCATION OF ALL THE EMPLOYEES
SELECT ENAME,LOC
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

# WAQTD DNAME AND SALARY FOR ALL THE EMPLOYEE WORKING IN ACCOUNTING.
SELECT DNAME,SAL
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO 
AND JOB = 'ACCOUNTING';

# WAQTD DNAME AND ANNUAL SALARY FOR ALL EMPLOYEES WHOS SALARY IS MORE THAN 2340
SELECT DNAME , SAL*12
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND SAL > 2340;

# WAQTD ENAME AND DNAME FOR EMPLOYEES HAVING CHARACTER 'A' IN THEIR DNAME
SELECT ENAME,DNAME
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND DNAME LIKE '%A';

# WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES WORKING AS SALESMAN
SELECT ENAME,DNAME
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND JOB = 'SALESAMN';

# WADTD DNAME AND JOB FOR ALL THE EMPLOYEES
# WHOS JOB AND DNAME STARTS WITH CHARACTER 'S'
SELECT DNAME,JOB 
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO 
AND JOB LIKE 'S%'
AND DNAME LIKE 'S%';


# WAQTD DNAME AND MGR NO FOR EMPLOYEES REPORTING TO 7839
SELECT DNAME,MGR 
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND EMP.MGR = 7839;

# WAQTD DNAME AND HIREDATE FOR EMPLOYEES HIRED
# AFTER 83 INTO ACCOUNTING OR RESEARCH DEPT
SELECT DNAME,HIREDATE 
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND HIREDATE > 83
AND DNAME IN ('ACCOUNTING','RESEARCH');

# WAQTD ENAME AND DNAME OF THE EMPLOYEES WHO ARE GETTING COMM IN DEPT 10 OR 30
SELECT ENAME, DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND EMP.COMM IS NOT NULL
AND EMP.DEPTNO IN (10,30);

# WAQTD DNAME AND EMPNO FOR ALL THE EMPLOYEES
# WHO'S EMPNO ARE (7839,7902) AND ARE WORKING IN LOC NEW YORK.
SELECT DNAME, EMPNO
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND EMP.EMPNO IN (7839,7902)
AND DEPT.LOC = 'NEW YORK';





