USE SCOTT;

# 71.WAQTD SMITHS REPORTING MANAGER'S NAME
SELECT MGR 
FROM EMP
WHERE ENAME = 'SMITHS';

# WAQTD ADAMS MANAGER'S MANAGER NAME
SELECT MGR 
FROM EMP
WHERE EMPNO = (SELECT MGR 
		        FROM EMP
		        WHERE ENAME = 'SMITHS');

# 73.WAQTD DNAME OF JONES MANAGER
SELECT DNAME 
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO 
				FROM EMP
                WHERE EMPNO = (SELECT MGR
								FROM EMP
								WHERE ENAME = 'JONES'));

# 74.WAQTD MILLER'S MANAGER'S SALARY
SELECT SAL 
FROM EMP
WHERE EMPNO = (SELECT MGR
		       FROM EMP
			   WHERE ENAME = 'MILLER');

# 75.WAQTD LOC OF SMITH'S MANAGER'S MANAGER.
SELECT LOC 
FROM DEPT 
WHERE DEPTNO = (SELECT DEPTNO
				FROM EMP
                WHERE EMPNO = (SELECT MGR
                               FROM EMP
                               WHERE EMPNO = (SELECT MGR
		                                      FROM EMP
		                                      WHERE ENAME = 'SMITH')));

# 76.WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE
SELECT ENAME 
FROM EMP
WHERE MGR = (SELECT EMPNO
			 FROM EMP
             WHERE ENAME = 'BLAKE');

# WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING
SELECT COUNT(*)
FROM EMP
WHERE MGR = (SELECT EMPNO
			 FROM EMP
             WHERE ENAME = 'KING');


# WAQTD DETAILS OF THE EMPLOYEES REPEPORTING TO JONES
SELECT *
FROM EMP
WHERE MGR = (SELECT EMPNO 
			 FROM EMP
             WHERE ENAME = 'JONES');

SELECT ENAME 
FROM EMP
WHERE MGR = (SELECT MGR 
			 FROM EMP
             WHERE ENAME = 'BLAKE');

# WAQTD NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER
SELECT COUNT(*)
FROM EMP
WHERE MGR = (SELECT MGR 
			 FROM EMP
             WHERE ENAME = 'FORD');