USE SCOTT;

# WAQTD 2ND MINIMUM SALARY.
SELECT MIN(SAL)
FROM EMP
WHERE SAL > (SELECT MIN(SAL)
			FROM EMP);
            
            
# WAQTD 5TH MAXIMUM SALARY
SELECT MAX(SAL)
FROM EMP
WHERE SAL < (SELECT MAX(SAL)
			FROM EMP 
            WHERE SAL <
            (SELECT MAX(SAL)
			FROM EMP
			WHERE SAL <
			(SELECT MAX(SAL)
			FROM EMP
			WHERE SAL <
            (SELECT MAX(SAL)
			FROM EMP))));

# WATQTD NAME OF THE EMPLOYEE EARNING 3RD MAXIMUM SALARY.
SELECT ENAME 
FROM EMP
WHERE SAL = (SELECT MAX(SAL)
			FROM EMP
            WHERE SAL < 
            (SELECT MAX(SAL)
			FROM EMP
            WHERE SAL <
            (SELECT MAX(SAL)
			FROM EMP)));

# WAQTD EMPNO OF THE EMPLOYEE EARNING 2ND MAXIMUM SALARY.
SELECT EMPNO
FROM EMP
WHERE SAL =	(SELECT MAX(SAL)
			FROM EMP
            WHERE SAL <
            (SELECT MAX(SAL)
			FROM EMP));
            
# WAQTD DEPARTMENT NAME OF THE EMPLOYEE GETTING 4TH MAX SALARY.
SELECT DNAME
FROM DEPT 
WHERE DEPTNO = (SELECT DEPTNO FROM EMP
                WHERE SAL = (SELECT MAX(SAL)
			FROM EMP
            WHERE SAL < 
			(SELECT MAX(SAL)
			FROM EMP
            WHERE SAL <
            (SELECT MAX(SAL)
			FROM EMP
            WHERE SAL <
            (SELECT MAX(SAL)
			FROM EMP)))));
            
            
# WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED 2ND
SELECT *
FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE)
				 FROM EMP
                 WHERE HIREDATE > (
                 SELECT MIN(HIREDATE)
                 FROM EMP));
			 
# WAQTD NAME OF THE EMPLOYEE WHO HIRED BEFORE THE LAST EMPLOYEE.
SELECT ENAME 
FROM EMP
WHERE HIREDATE = (SELECT (HIREDATE)
				  FROM EMP
                  WHERE HIREDATE < (
                  SELECT MAX(HIREDATE)
                  FROM EMP));
                  
USE SCOTT;
# WAQTD LOC OF THE EMPLOYEE WHO WAS HIRED FIRST.
SELECT LOC 
FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE) 
				 FROM EMP);

# WAQTD DETAILS OF THE EMPLOYEE EARNING 7TH MINIMUM SALARY.
SELECT *
FROM EMP
WHERE SAL > (SELECT MIN(SAL)
			FROM EMP
            WHERE SAL >
			(SELECT MIN(SAL)
			FROM EMP
            WHERE SAL >
            (SELECT MIN(SAL)
			FROM EMP
            WHERE SAL >
            (SELECT MIN(SAL)
			FROM EMP
            WHERE SAL >
            (SELECT MIN(SAL)
			FROM EMP
            WHERE SAL >
            (SELECT MIN(SAL)
			FROM EMP
            WHERE SAL >
            (SELECT MIN(SAL)
			FROM EMP )))))));

# WAQTD DNAME OF THE EMPLOYEE GETTING 2ND MAXIMUM SALARY
SELECT DNAME 
FROM DEPT 
WHERE DEPTNO = (SELECT DEPTNO
				FROM EMP 
                WHERE SAL = 
			    (SELECT MAX(SAL)
				FROM EMP 
                WHERE SAL <
				(SELECT MAX(SAL)
				FROM EMP)));

