USE SCOTT;

# 1.WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS
SELECT ENAME 
FROM EMP
WHERE SAL > ( SELECT SAL FROM EMP WHERE ENAME = 'ADAMS');

# WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING
SELECT ENAME , SAL 
FROM EMP
WHERE SAL < ( SELECT SAL FROM EMP WHERE ENAME = 'KING');

# WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES
SELECT ENAME, DEPTNO 
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'JONES');

# WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES
SELECT ENAME,JOB 
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'JAMES');

# WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARDS ANNUAL SALARY.
SELECT EMPNO,ENAME,SAL*12 AS ANNUAL_SALARY 
FROM EMP 
WHERE SAL*12 > (SELECT SAL * 12 FROM EMP WHERE ENAME = 'WARD'); 

# WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT
SELECT ENAME,HIREDATE 
FROM EMP
WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'SCOTT');

# WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED AFTER THE PRESIDENT
SELECT ENAME,HIREDATE 
FROM EMP
WHERE HIREDATE > (SELECT HIREDATE FROM EMP WHERE JOB = 'PRESIDENT');

# WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839
SELECT ENAME,SAL 
FROM EMP
WHERE SAL < (SELECT SAL FROM EMP WHERE EMPNO = 7839);

# WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER
SELECT *
FROM EMP
WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'MILLER');

# WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN
SELECT ENAME,EMPNO
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'ALLEN');

# WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN
SELECT ENAME,SAL 
FROM EMP 
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'MILLER') 
AND SAL < (SELECT SAL FROM EMP WHERE ENAME = 'ALLEN');

# WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH
SELECT *
FROM EMP
WHERE DEPTNO = 20 AND JOB = (SELECT JOB FROM EMP WHERE ENAME = 'SMITH');















