# WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT 
SELECT ENAME 
FROM EMP 
WHERE SAL > ( SELECT SAL FROM EMP WHERE ENAME = 'SCOTT')
AND DEPTNO = ( SELECT DEPTNO FROM DEPT WHERE DNAME = 'ACCOUNTING');

# WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO
SELECT *
FROM EMP 
WHERE JOB = 'MANAGER'  
AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = 'CHICAGO');

# WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING
SELECT ENAME,SAL 
FROM EMP 
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'KING')
AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE JOB = 'ACCOUNTING');

# WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTEMENT SALES
SELECT *
FROM EMP
WHERE JOB = 'SALESMAN' 
AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE JOB = 'SALES');

# WAQTD NAME , SAL , JOB , HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING
SELECT ENAME, SAL, JOB, HIREDATE
FROM EMP
WHERE DEPTNO IN (
    SELECT DEPTNO
    FROM DEPT
    WHERE DNAME = 'OPERATIONS'
)
AND HIREDATE < (
    SELECT HIREDATE
    FROM EMP
    WHERE ENAME = 'KING'
);

# DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'.
SELECT *
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME LIKE '%S');

# WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER ‘A’ IN IT .
SELECT DNAME
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%A%'); 

# WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS SALARY IS RUPEES 800 
SELECT DNAME,LOC 
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE SAL = 800); 

# WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (
    SELECT DEPTNO
    FROM EMP
    WHERE COMM IS NOT NULL
);


# WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40
SELECT LOC
FROM DEPT
WHERE DEPTNO IN (
    SELECT DEPTNO
    FROM EMP
    WHERE COMM IS NOT NULL
    AND DEPTNO = 40
);


